---
output: html_fragment
---

<!-- text for activity 3 -->

The upper panel of controls define the conditions---concentrations and volumes---for the titration of a diprotic weak acid or weak base titrand using a strong base or a strong acid titrant. Use the pK sliders to set the two pK values for the titrands. The sliders for concentration are logarithmic; the titrand's default concentration is $10^{-1} = 0.10 \text{ M}$ and the titrant's default concentration is $10^{-0.7} = 0.2 \text{ M}$. The lower panel of controls defines the range of volumes to use when displaying the titration curve and selects the indicator. The color of the titration curve mimics the indicator's color during the titration. The indicator's endpoint is defined here as the average of its acidic and basic limits.

**Exercise 1**. Describe the effect of the titrand's two p$K_a$ or p$K_b$ values, its concentration and volume, and the titrant's concentration on the shape and position of the titration curve along the *x*-axis and the change in pH at each of its two equivalence points. Not all combinations of these variables will yield a useful titration curve. Are the effects the same when titrating a diprotic weak acid and titrating a diprotic weak base?

**Exercise 2**. Which indicators are suitable for a titration of a diprotic weak acid with a strong base using [titrand] = [titrant] = 0.10 M? Are there indicators that are useful across a wider range of concentrations? Repeat for the titration of a diprotic weak base with a strong acid.

**Exercise 3**. When we use an indicator to signal the endpoint, we usually do not record the titration curve itself. In the absence of suitable indicator, however, we must record the titration curve by measuring the pH of the titration mixture as we add the titrant. Is the change in pH sufficient to allow you to identify the equivalence point when [titrand] = [titrant] = 10^-3^ M?

**Exercise 4**. Commercial washing soda is 30--40 %w/w $\ce{Na2CO3}$. Propose a set of conditions---mass of washing soda, molarity of HCl, and choice of acid-base indicator---that will allow you to determine the amount of $\ce{Na2CO3}$ in samples of washing soda when using HCl as a titrant. All titrations should have endpoints between 20.0 mL and 40.0 mL.
