---
output: html_document
---

<!-- The following script makes it possible to use the mhchem -->

<!-- latex package in a .Rmd file and to knit it into an .html file -->

<!-- the font size is scaled to 90% to match text -->

```{=html}
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: {
    extensions: ["[Contrib]/mhchem/mhchem.js"]
}
});
MathJax.Hub.Config({ 
        "HTML-CSS": { scale: 90 }, 
        SVG: { linebreaks: { automatic:true } }, 
 });
</script>
```
<!-- text for introduction -->

An acid-base titration is a quantitative analytical method in which we determine the concentration of an acid or a base---the titrand---by the controlled addition to the titrand of a strong base or a strong acid---the titrant---until the acid and the base react in a known stoichiometric ratio.   

#### Titration Curves and Visual Indicators

The figure on the lower right---the titration of a strong acid titrand, HCl, using a strong base titrant, NaOH---is a titration curve. It is recorded by placing the NaOH in a buret and slowly adding it to the solution of HCl while monitoring the titration mixture's pH. As discussed further below, a visual indicator---an organic dye, such as methyl red, whose color varies with pH---is often included. The color of the titration curve shows the indicator's color during the titration. 

#### Equivalence Points and Endpoints

A titration's equivalence point is the pH and volume where the initial moles of titrand equals the stoichiometric moles of titrant delivered. Locating the equivalence point is the essential measurement in an acid-base titration. A solution of a strong acid, such as HCl, is acidic with a pH below 7. As we add a strong base, such as NaOH, the pH increases but remains below 7 as HCl remains in excess. The pH rises above 7 when the moles of NaOH added exceeds the moles of HCl initially present. When the pH is 7, the moles of NaOH added is the same as the moles of HCl initially present; this is the equivalence point.

If we know the equivalence point's pH in advance, then we can titrate to this exact pH; this is, however, a rare circumstance. Instead, we either continue the titration until the pH levels off, locating the equivalence point as the greatest slope in the middle of the steeply rising change in pH, or we use a visual indicator that changes color at a pH close to the equivalence point. The figure on the upper right, for example, shows the color of the indicator methyl red in (a) its red, weak acid form at pHs < 4.2 and (c) its yellow, weak base form at pHs > 6.3. For pHs greater than 4.2 but less than 6.3 the indicator is present in (b) both its acid and its base form, and is orange; this is called the titration's endpoint. In a well-designed acid-base titration, the difference between the equivalence point's volume and the endpoint's volume is small.

 
